### ISSUE TITLE
Add transit layer to basemap

### ISSUE THREAD

**Issue by Siqister** [Siqister/cartodb_test_app#11]
Commuter rail station and commuter rail lines

Maybe we can do this on the basemap tiles directly through Tilemill?

**Comment by allthesignals** [comment]
We can tile commuter data with transparencies that overlay the existing basemap. Or as you suggest, create a custom basemap that includes the transit data.

**Comment by allthesignals** [comment]
http://gis.stackexchange.com/questions/116205/multiple-simultaneous-tilelayers-in-leaflet
