### ISSUE TITLE
Add 3D buildings to map layer

### ISSUE THREAD

**Issue by Siqister** [Siqister/cartodb_test_app#14]
Already did this for Springfield and Brockton. Copy and paste.

**Comment by allthesignals** [comment]
Add for Revere, Lynn

**Comment by allthesignals** [comment]
Asking Kyle for SVG data.

**Comment by allthesignals** [comment]
Working on pulling bounding box extents for SVG files.

**Comment by allthesignals** [comment]
@Siqister sorry to ping you on this, but I'm struggling a bit with finding the best way to project new SVGs in Leaflet. How did you derive the bounding box information correctly from the svg files? It's not clear how Leaflet projects the SVG through L.ImageOverlay, whether using the full extend of the SVG document or just the `<g>` "group" element... anyway, I've tried georeferencing a rasterized version of the SVGs and even looked into affine transformation to get the correct projected bounding box, but I suspect there's a better way somehow. No rush, but your thoughts are appreciated! Thanks.
