### ISSUE TITLE
Edit Assets and Investments

### ISSUE THREAD

**Issue by allthesignals** [Siqister/cartodb_test_app#23]
Assets and Investments are editable, but their tpyes and subtypes, among other fields, are not editable. They need to all be editable. 
- [x] Assets
- [x] Investments

**Comment by allthesignals** [comment]
We must refactor using this: https://github.com/powmedia/backbone-forms

**Comment by allthesignals** [comment]
Some styling issues remain.

**Comment by IanJakus** [comment]
I love the editing menu, it works great. @allthesignals
