### ISSUE TITLE
Open Date / Closed date for feature points 

### ISSUE THREAD

**Issue by IanJakus** [Siqister/cartodb_test_app#29]
Add timestamp for open and close. IF feature point is closed do not show on map but leave in database.

**Comment by allthesignals** [comment]
@IanJakus Starting this now.

**Comment by allthesignals** [comment]
@IanJakus Just want to confirm that this is correct. Please see commit message in this thread. Thanks.

**Comment by IanJakus** [comment]
Hey Matt, I cannot save a point currently while leaving open and close dates Null. Can you address this?

Also when adding a feature point the icon comes up first as an investment type icon. This is not critical but something to be addressed if possible.

Thanks,

Ian

**Comment by allthesignals** [comment]
@IanJakus Got it. Thanks for the feedback. Reopening this.

**Comment by allthesignals** [comment]
- [x] Allow saving points when open and close dates are null.
- [ ] Make sure new points use the correct icons.
